#!/usr/bin/env bash

die () {
    echo "ERROR: ${1}"
    exit 1
}

timestamp () {
    echo "[$(date '+%I:%M:%S %p')]"
}

check_depending_env () {
  if [ -n "${DEPENDING_ENVIRONMENT_VARS}" ]; then
    MISSING_ENVIRONMENT_VARS=()
    echo -n "* Checking depending environment variables "
    for e in ${DEPENDING_ENVIRONMENT_VARS}; do
      if [ ! -v "${e}" ]; then
        MISSING_ENVIRONMENT_VARS+=("${e}")
      fi
    done
    if [ ${#MISSING_ENVIRONMENT_VARS[@]} -gt 0 ]; then
      echo "[missing variables]"
      for missing in "${MISSING_ENVIRONMENT_VARS[@]}"; do
        echo " * ${missing}"
      done
      echo
      die "Missing environment variables"
    fi
    echo -n "[done]"
    echo
  fi
}

# When enabled, will write all executed commands to the terminal.  Can be helpful for visualizing script's control flow.
[[ ${DOCKER_DEBUG} ]] && set -x

# Automatically allow execution for all scripts.  When adding new hooks, we shouldn't also have think about granting execute permission in the
# Dockerfile as well. If you want to disable a hook, rename it.
chmod +x /init/setup /hooks/{entrypoint-pre.d/*,entrypoint-run,entrypoint-exec,supervisord-pre.d/*,supervisord-ready} 2> /dev/null || true

entrypoint_pre=$(ls /hooks/entrypoint-pre.d/* 2>/dev/null | sort -n )
if [ "$entrypoint_pre" != "" ]; then
    for hook in $entrypoint_pre; do
        echo "$(timestamp) Executing hook ${hook}"
        /bin/bash -c "${hook}"

        if [ "$?" != "0" ]; then
            die "hook ${hook}} returned a non-zero exit status '$?'"
        fi
    done
fi

[[ -f "/hooks/entrypoint-pre" ]] && echo "The /hooks/entrypoint-pre hook has been replaced with /hooks/entrypoint-pre.d/*" && exit 1

[[ -f "/init/setup" ]] && /init/setup

eval ${SETUP:-}

case ${1} in
  run)
    check_depending_env
    [[ -f "/hooks/entrypoint-run" ]] && /hooks/entrypoint-run
    if [[ -e /init/supervisord && -d /etc/supervisor ]]; then
      # Use exec so we replace our current process so signals can get through
      exec /bin/bash /init/supervisord
    else
      exec /bin/bash
    fi
    ;;
  *)
    [[ -f "/hooks/entrypoint-exec" ]] && /hooks/entrypoint-exec
    exec $*
    ;;
esac
